package com.aladinjunior.coletor.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF646116)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFECE68D)
val onPrimaryContainerLight = Color(0xFF1E1C00)
val secondaryLight = Color(0xFF626042)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8E4BE)
val onSecondaryContainerLight = Color(0xFF1E1C05)
val tertiaryLight = Color(0xFF3F6655)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC0ECD6)
val onTertiaryContainerLight = Color(0xFF002115)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF9EB)
val onBackgroundLight = Color(0xFF1D1C14)
val surfaceLight = Color(0xFFFEF9EB)
val onSurfaceLight = Color(0xFF1D1C14)
val surfaceVariantLight = Color(0xFFE7E3D1)
val onSurfaceVariantLight = Color(0xFF49473A)
val outlineLight = Color(0xFF7A7768)
val outlineVariantLight = Color(0xFFCAC7B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323128)
val inverseOnSurfaceLight = Color(0xFFF5F1E3)
val inversePrimaryLight = Color(0xFFCFCA74)


val primaryLightMediumContrast = Color(0xFF484500)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7B772B)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF464429)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF787657)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF224A3A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF557D6A)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF9EB)
val onBackgroundLightMediumContrast = Color(0xFF1D1C14)
val surfaceLightMediumContrast = Color(0xFFFEF9EB)
val onSurfaceLightMediumContrast = Color(0xFF1D1C14)
val surfaceVariantLightMediumContrast = Color(0xFFE7E3D1)
val onSurfaceVariantLightMediumContrast = Color(0xFF454336)
val outlineLightMediumContrast = Color(0xFF615F51)
val outlineVariantLightMediumContrast = Color(0xFF7D7B6C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF323128)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5F1E3)
val inversePrimaryLightMediumContrast = Color(0xFFCFCA74)


val primaryLightHighContrast = Color(0xFF252300)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF484500)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF24230B)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF464429)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00281B)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF224A3A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF9EB)
val onBackgroundLightHighContrast = Color(0xFF1D1C14)
val surfaceLightHighContrast = Color(0xFFFEF9EB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE7E3D1)
val onSurfaceVariantLightHighContrast = Color(0xFF252419)
val outlineLightHighContrast = Color(0xFF454336)
val outlineVariantLightHighContrast = Color(0xFF454336)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF323128)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFF5F096)


val primaryDark = Color(0xFFCFCA74)
val onPrimaryDark = Color(0xFF343200)
val primaryContainerDark = Color(0xFF4C4900)
val onPrimaryContainerDark = Color(0xFFECE68D)
val secondaryDark = Color(0xFFCCC8A4)
val onSecondaryDark = Color(0xFF333118)
val secondaryContainerDark = Color(0xFF4A482C)
val onSecondaryContainerDark = Color(0xFFE8E4BE)
val tertiaryDark = Color(0xFFA5D0BB)
val onTertiaryDark = Color(0xFF0D3728)
val tertiaryContainerDark = Color(0xFF264E3E)
val onTertiaryContainerDark = Color(0xFFC0ECD6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF14140C)
val onBackgroundDark = Color(0xFFE6E2D5)
val surfaceDark = Color(0xFF14140C)
val onSurfaceDark = Color(0xFFE6E2D5)
val surfaceVariantDark = Color(0xFF49473A)
val onSurfaceVariantDark = Color(0xFFCAC7B5)
val outlineDark = Color(0xFF949181)
val outlineVariantDark = Color(0xFF49473A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E2D5)
val inverseOnSurfaceDark = Color(0xFF323128)
val inversePrimaryDark = Color(0xFF646116)


val primaryDarkMediumContrast = Color(0xFFD3CE78)
val onPrimaryDarkMediumContrast = Color(0xFF181700)
val primaryContainerDarkMediumContrast = Color(0xFF989444)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD0CCA8)
val onSecondaryDarkMediumContrast = Color(0xFF181702)
val secondaryContainerDarkMediumContrast = Color(0xFF959271)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFA9D4BF)
val onTertiaryDarkMediumContrast = Color(0xFF001B11)
val tertiaryContainerDarkMediumContrast = Color(0xFF709986)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF14140C)
val onBackgroundDarkMediumContrast = Color(0xFFE6E2D5)
val surfaceDarkMediumContrast = Color(0xFF14140C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFBED)
val surfaceVariantDarkMediumContrast = Color(0xFF49473A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCFCBBA)
val outlineDarkMediumContrast = Color(0xFFA6A393)
val outlineVariantDarkMediumContrast = Color(0xFF868374)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E2D5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B2A22)
val inversePrimaryDarkMediumContrast = Color(0xFF4D4A00)


val primaryDarkHighContrast = Color(0xFFFFFBED)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD3CE78)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFBED)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFD0CCA8)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFEDFFF4)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA9D4BF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF14140C)
val onBackgroundDarkHighContrast = Color(0xFFE6E2D5)
val surfaceDarkHighContrast = Color(0xFF14140C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49473A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFBED)
val outlineDarkHighContrast = Color(0xFFCFCBBA)
val outlineVariantDarkHighContrast = Color(0xFFCFCBBA)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E2D5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2D2B00)








